version: '3.8'

services:
  # --- BASES DE DATOS INDEPENDIENTES ---
  
  auth_db:
    image: postgres:15-alpine
    container_name: auth_db
    environment:
      POSTGRES_DB: catire_auth_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - t4_network

  catalog_db:
    image: postgres:15-alpine
    container_name: catalog_db
    environment:
      POSTGRES_DB: catire_catalog_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - t4_network

  order_db:
    image: postgres:15-alpine
    container_name: order_db
    environment:
      POSTGRES_DB: catire_order_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - t4_network

  order_db_audit:
    image: mongo:6-jammy
    container_name: order_db_audit
    networks:
      - t4_network

  finance_config_db:
    image: postgres:15-alpine
    container_name: finance_config_db
    environment:
      POSTGRES_DB: catire_finance_config_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - t4_network


  # --- MICROSERVICIOS ---

  auth-service:
    build: 
      context: ./auth-service
      dockerfile: ../Dockerfile.dev
    volumes:
      - ./auth-service:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@auth_db:5432/catire_auth_db
    depends_on:
      - auth_db
    networks:
      - t4_network

  catalog-service:
    build: 
      context: ./catalog-service
      dockerfile: ../Dockerfile.dev
    volumes:
      - ./catalog-service:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@catalog_db:5432/catire_catalog_db
    depends_on:
      - catalog_db
    networks:
      - t4_network

  order-service:
    build: 
      context: ./order-service
      dockerfile: ../Dockerfile.dev
    volumes:
      - ./order-service:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@order_db:5432/catire_order_db
      - MONGO_URL=mongodb://order_db_audit:27017/catire_order_db
    depends_on:
      - order_db
      - order_db_audit
    networks:
      - t4_network

  finance-config-service:
    build: 
      context: ./finance-config-service
      dockerfile: ../Dockerfile.dev
    volumes:
      - ./finance-config-service:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@finance_config_db:5432/catire_finance_config_db
    depends_on:
      - finance_config_db
    networks:
      - t4_network

  # Gateway (Nginx)
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - t4_network

networks:
  t4_network:
    driver: bridge