events {
  worker_connections 1024;
}

http {
  upstream auth_backend {
    server auth-service:3000;
  }

  upstream catalog_backend {
    server catalog-service:3010;
  }

  upstream order_backend {
    server order-service:3020;
  }

  upstream finance_config_backend {
    server finance-config-service:3030;
  }

  server {
    listen 80;
    server_name localhost;

    location /api/auth/ {
      proxy_pass http://auth_backend/;
      proxy_set_header Host $host;
    }

    location /api/catalog/ {
      proxy_pass http://catalog_backend/;
      proxy_set_header Host $host;
    }

    location /api/order/ {
      proxy_pass http://order_backend/;
      proxy_set_header Host $host;
    }

    location /api/finance_config/ {
      proxy_pass http://finance_config_backend/;
      proxy_set_header Host $host;
    }
  }
}