worker_processes 1;

events { 
  worker_connections 1024; 
}

http {
  sendfile on;

  upstream auth_upstream {
    server auth-service:3000;
  }

  upstream catalog_upstream {
    server catalog-service:3000;
  }

  upstream order_upstream {
    server order-service:3000;
  }

  upstream finance_config_upstream {
    server finance-config-service:3000;
  }

  server {
    listen 80;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/auth/ {
      proxy_pass http://auth_upstream/;
    }

    location /api/catalog/ {
      proxy_pass http://catalog_upstream/;
    }

    location /api/orders/ {
      proxy_pass http://order_upstream/;
    }

    location /api/finance/ {
      proxy_pass http://finance_config_upstream/;
    }
  }
}